### ISSUE TITLE
There's a problem opening IBM Notes sessions. Java permissions needed.

### ISSUE THREAD

**Issue by mariosotil** [mariosotil/river-framework#1]
When I'm trying to open a session using the IBM Notes wrapper, I get this stack traces:

```
org.riverframework.RiverException: There's a problem opening the session. Maybe, you will need to check the parameters.
    at org.riverframework.River.getSession(River.java:111)
    at JavaAgent.NotesMain(Unknown Source)
    at lotus.domino.AgentBase.runNotes(Unknown Source)
    at lotus.domino.NotesThread.run(Unknown Source)
Caused by: java.security.AccessControlException: Access denied (java.lang.reflect.ReflectPermission suppressAccessChecks)
    at java.security.AccessController.throwACE(AccessController.java:100)
    at java.security.AccessController.checkPermission(AccessController.java:174)
```

or

```
Exception in thread "AgentThread: JavaAgent" java.lang.ExceptionInInitializerError
    at java.lang.J9VMInternals.initialize(J9VMInternals.java:222)
    at JavaAgent.NotesMain(Unknown Source)
    at lotus.domino.AgentBase.runNotes(Unknown Source)
    at lotus.domino.NotesThread.run(Unknown Source)
Caused by: java.security.AccessControlException: Access denied (java.util.logging.LoggingPermission control)
    at java.security.AccessController.throwACE(AccessController.java:100)
    at java.security.AccessController.checkPermission(AccessController.java:174)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:544)
```

**Comment by mariosotil** [comment]
**Workaround:** Until the 0.2.10 version, in a development environment, you can add this line to your `lib\security\java.policy` file at the `grant` section of your JVM:

```
permission java.security.AllPermission;
```

In a production environment, these lines should be enough:

```
permission java.util.logging.LoggingPermission "control"; 
permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
```

If you're trying to use the libraries into an XPages app, you can copy the Jar files to the jvm\lib\ext folder

**Comment by mariosotil** [comment]
In the 0.2.11 release was fixed the problem with `LoggingPermission "control".

About the problem with `ReflectPermission "suppressAccessChecks"`  you have two options in a production environment:

A. Modify the `lib\security\java.policy` and add only this line:

```
permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
```

Or

B. Copy the River Framework Jar files into the `jvm\lib\ext` folder

Just in case, this permission is needed to use reflection to check if it's possible to recycle IBM Notes java objects.
